# Check Lua Formatting
name: Check Lua Formatting
on: pull_request

permissions: {}

jobs:
  stylua-check:
    if: github.repository == 'nvim-lua/kickstart.nvim'
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
